In [0]:
sc

In [0]:
print(spark)

In [0]:
# a)Create HR_Employee Pysaprk dataFrame. 
HR=spark.read.csv("dbfs:/FileStore/tables/HR_Employee.csv",header= True ,inferSchema=True)
HR.show()

+----------+--------------------+--------------------+---------+------+---+-------------+-------------+--------------+-----------------+--------------+--------+---------------+----------+------+----------+--------+------+-----------------------+---------------+---------------------+---------------+------------------+
|EmployeeID|          Department|             JobRole|Attrition|Gender|Age|MaritalStatus|    Education|EducationField|   BusinessTravel|JobInvolvement|JobLevel|JobSatisfaction|Hourlyrate|Income|Salaryhike|OverTime|Workex|YearsSinceLastPromotion|EmpSatisfaction|TrainingTimesLastYear|WorkLifeBalance|Performance_Rating|
+----------+--------------------+--------------------+---------+------+---+-------------+-------------+--------------+-----------------+--------------+--------+---------------+----------+------+----------+--------+------+-----------------------+---------------+---------------------+---------------+------------------+
|         1|               Sales|     Sales Executive|      Yes|Female| 41|       Single|      College| Life Sciences|    Travel_Rarely|          High|       2|      Very High|        94|  5993|        11|     Yes|     8|                      0|         Medium|                    0|            Bad|         Excellent|
|         2|Research & Develo...|  Research Scientist|       No|  Male| 49|      Married|Below College| Life Sciences|Travel_Frequently|        Medium|       2|         Medium|        61|  5130|        23|      No|    10|                      1|           High|                    3|         Better|       Outstanding|
|         3|Research & Develo...|Laboratory Techni...|      Yes|  Male| 37|       Single|      College|         Other|    Travel_Rarely|        Medium|       1|           High|        92|  2090|        15|     Yes|     7|                      0|      Very High|                    3|         Better|         Excellent|
|         4|Research & Develo...|  Research Scientist|       No|Female| 33|      Married|       Master| Life Sciences|Travel_Frequently|          High|       1|           High|        56|  2909|        11|     Yes|     8|                      3|      Very High|                    3|         Better|         Excellent|
|         5|Research & Develo...|Laboratory Techni...|       No|  Male| 27|      Married|Below College|       Medical|    Travel_Rarely|          High|       1|         Medium|        40|  3468|        12|      No|     6|                      2|            Low|                    3|         Better|         Excellent|
|         6|Research & Develo...|Laboratory Techni...|       No|  Male| 32|       Single|      College| Life Sciences|Travel_Frequently|          High|       1|      Very High|        79|  3068|        13|      No|     8|                      3|      Very High|                    2|           Good|         Excellent|
|         7|Research & Develo...|Laboratory Techni...|       No|Female| 59|      Married|     Bachelor|       Medical|    Travel_Rarely|     Very High|       1|            Low|        81|  2670|        20|     Yes|    12|                      0|           High|                    3|           Good|       Outstanding|
|         8|Research & Develo...|Laboratory Techni...|       No|  Male| 30|     Divorced|Below College| Life Sciences|    Travel_Rarely|          High|       1|           High|        67|  2693|        22|      No|     1|                      0|      Very High|                    2|         Better|       Outstanding|
|         9|Research & Develo...|Manufacturing Dir...|       No|  Male| 38|       Single|     Bachelor| Life Sciences|Travel_Frequently|        Medium|       3|           High|        44|  9526|        21|      No|    10|                      1|      Very High|                    2|         Better|       Outstanding|
|        10|Research & Develo...|Healthcare Repres...|       No|  Male| 36|      Married|     Bachelor|       Medical|    Travel_Rarely|          High|       2|           High|        94|  5237|        13|      No|    17|                      7|           High|                    3|           Good|         Excellent|
|        11|Research & Develo...|Laboratory Techni...|       No|  Male| 35|      Married|     Bachelor|       Medical|    Travel_Rarely|     Very High|       1|         Medium|        84|  2426|        13|      No|     6|                      0|            Low|                    5|         Better|         Excellent|
|        12|Research & Develo...|Laboratory Techni...|       No|Female| 29|       Single|      College| Life Sciences|    Travel_Rarely|        Medium|       2|           High|        49|  4193|        12|     Yes|    10|                      0|      Very High|                    3|         Better|         Excellent|
|        13|Research & Develo...|  Research Scientist|       No|  Male| 31|     Divorced|Below College| Life Sciences|    Travel_Rarely|          High|       1|           High|        31|  2911|        17|      No|     5|                      4|            Low|                    1|           Good|         Excellent|
|        14|Research & Develo...|Laboratory Techni...|       No|  Male| 34|     Divorced|      College|       Medical|    Travel_Rarely|          High|       1|      Very High|        93|  2661|        11|      No|     3|                      1|         Medium|                    2|         Better|         Excellent|
|        15|Research & Develo...|Laboratory Techni...|      Yes|  Male| 28|       Single|     Bachelor| Life Sciences|    Travel_Rarely|        Medium|       1|           High|        50|  2028|        14|     Yes|     6|                      0|           High|                    4|         Better|         Excellent|
|        16|Research & Develo...|Manufacturing Dir...|       No|Female| 29|     Divorced|       Master| Life Sciences|    Travel_Rarely|     Very High|       3|            Low|        51|  9980|        11|      No|    10|                      8|         Medium|                    1|         Better|         Excellent|
|        17|Research & Develo...|  Research Scientist|       No|  Male| 32|     Divorced|      College| Life Sciences|    Travel_Rarely|     Very High|       1|         Medium|        80|  3298|        12|     Yes|     7|                      0|            Low|                    5|           Good|         Excellent|
|        18|Research & Develo...|Laboratory Techni...|       No|  Male| 22|     Divorced|      College|       Medical|       Non-Travel|     Very High|       1|      Very High|        96|  2935|        13|     Yes|     1|                      0|      Very High|                    2|           Good|         Excellent|
|        19|               Sales|             Manager|       No|Female| 53|      Married|       Master| Life Sciences|    Travel_Rarely|        Medium|       4|      Very High|        78| 15427|        16|      No|    31|                      3|            Low|                    3|         Better|         Excellent|
|        20|Research & Develo...|  Research Scientist|       No|  Male| 38|       Single|     Bachelor| Life Sciences|    Travel_Rarely|          High|       1|      Very High|        45|  3944|        11|     Yes|     6|                      1|      Very High|                    3|         Better|         Excellent|
+----------+--------------------+--------------------+---------+------+---+-------------+-------------+--------------+-----------------+--------------+--------+---------------+----------+------+----------+--------+------+-----------------------+---------------+---------------------+---------------+------------------+
only showing top 20 rows

In [0]:
#b)	Show printSchema & show 10 rows of Dataset
HR.printSchema()
HR.show(10)

root
 |-- EmployeeID: integer (nullable = true)
 |-- Department: string (nullable = true)
 |-- JobRole: string (nullable = true)
 |-- Attrition: string (nullable = true)
 |-- Gender: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- MaritalStatus: string (nullable = true)
 |-- Education: string (nullable = true)
 |-- EducationField: string (nullable = true)
 |-- BusinessTravel: string (nullable = true)
 |-- JobInvolvement: string (nullable = true)
 |-- JobLevel: integer (nullable = true)
 |-- JobSatisfaction: string (nullable = true)
 |-- Hourlyrate: integer (nullable = true)
 |-- Income: integer (nullable = true)
 |-- Salaryhike: integer (nullable = true)
 |-- OverTime: string (nullable = true)
 |-- Workex: integer (nullable = true)
 |-- YearsSinceLastPromotion: integer (nullable = true)
 |-- EmpSatisfaction: string (nullable = true)
 |-- TrainingTimesLastYear: integer (nullable = true)
 |-- WorkLifeBalance: string (nullable = true)
 |-- Performance_Rating: string (nullable = true)

+----------+--------------------+--------------------+---------+------+---+-------------+-------------+--------------+-----------------+--------------+--------+---------------+----------+------+----------+--------+------+-----------------------+---------------+---------------------+---------------+------------------+
|EmployeeID|          Department|             JobRole|Attrition|Gender|Age|MaritalStatus|    Education|EducationField|   BusinessTravel|JobInvolvement|JobLevel|JobSatisfaction|Hourlyrate|Income|Salaryhike|OverTime|Workex|YearsSinceLastPromotion|EmpSatisfaction|TrainingTimesLastYear|WorkLifeBalance|Performance_Rating|
+----------+--------------------+--------------------+---------+------+---+-------------+-------------+--------------+-----------------+--------------+--------+---------------+----------+------+----------+--------+------+-----------------------+---------------+---------------------+---------------+------------------+
|         1|               Sales|     Sales Executive|      Yes|Female| 41|       Single|      College| Life Sciences|    Travel_Rarely|          High|       2|      Very High|        94|  5993|        11|     Yes|     8|                      0|         Medium|                    0|            Bad|         Excellent|
|         2|Research & Develo...|  Research Scientist|       No|  Male| 49|      Married|Below College| Life Sciences|Travel_Frequently|        Medium|       2|         Medium|        61|  5130|        23|      No|    10|                      1|           High|                    3|         Better|       Outstanding|
|         3|Research & Develo...|Laboratory Techni...|      Yes|  Male| 37|       Single|      College|         Other|    Travel_Rarely|        Medium|       1|           High|        92|  2090|        15|     Yes|     7|                      0|      Very High|                    3|         Better|         Excellent|
|         4|Research & Develo...|  Research Scientist|       No|Female| 33|      Married|       Master| Life Sciences|Travel_Frequently|          High|       1|           High|        56|  2909|        11|     Yes|     8|                      3|      Very High|                    3|         Better|         Excellent|
|         5|Research & Develo...|Laboratory Techni...|       No|  Male| 27|      Married|Below College|       Medical|    Travel_Rarely|          High|       1|         Medium|        40|  3468|        12|      No|     6|                      2|            Low|                    3|         Better|         Excellent|
|         6|Research & Develo...|Laboratory Techni...|       No|  Male| 32|       Single|      College| Life Sciences|Travel_Frequently|          High|       1|      Very High|        79|  3068|        13|      No|     8|                      3|      Very High|                    2|           Good|         Excellent|
|         7|Research & Develo...|Laboratory Techni...|       No|Female| 59|      Married|     Bachelor|       Medical|    Travel_Rarely|     Very High|       1|            Low|        81|  2670|        20|     Yes|    12|                      0|           High|                    3|           Good|       Outstanding|
|         8|Research & Develo...|Laboratory Techni...|       No|  Male| 30|     Divorced|Below College| Life Sciences|    Travel_Rarely|          High|       1|           High|        67|  2693|        22|      No|     1|                      0|      Very High|                    2|         Better|       Outstanding|
|         9|Research & Develo...|Manufacturing Dir...|       No|  Male| 38|       Single|     Bachelor| Life Sciences|Travel_Frequently|        Medium|       3|           High|        44|  9526|        21|      No|    10|                      1|      Very High|                    2|         Better|       Outstanding|
|        10|Research & Develo...|Healthcare Repres...|       No|  Male| 36|      Married|     Bachelor|       Medical|    Travel_Rarely|          High|       2|           High|        94|  5237|        13|      No|    17|                      7|           High|                    3|           Good|         Excellent|
+----------+--------------------+--------------------+---------+------+---+-------------+-------------+--------------+-----------------+--------------+--------+---------------+----------+------+----------+--------+------+-----------------------+---------------+---------------------+---------------+------------------+
only showing top 10 rows

In [0]:
HR.createOrReplaceTempView("employee")

In [0]:
#c)	Most employee is working in which department
spark.sql("select Department ,count(*) as most_employee from employee group by Department order by most_employee desc ").show()

+--------------------+-------------+
|          Department|most_employee|
+--------------------+-------------+
|Research & Develo...|          961|
|               Sales|          445|
|     Human Resources|           63|
+--------------------+-------------+

In [0]:
# d)Highest number of job roles
spark.sql("select Max(JobRole) as Job_role,count(*) as most_employee from employee ").show()

+--------------------+-------------+
|            Job_role|most_employee|
+--------------------+-------------+
|Sales Representative|         1469|
+--------------------+-------------+

In [0]:
# g)    Mostly hired employee have qualification
spark.sql("select Education, count(*) as Num_Employee from employee  group by Education order by Num_Employee desc").show()

+-------------+------------+
|    Education|Num_Employee|
+-------------+------------+
|     Bachelor|         572|
|       Master|         398|
|      College|         282|
|Below College|         169|
|       Doctor|          48|
+-------------+------------+

In [0]:
# e)    Which gender have higher strength as workforce?
spark.sql("select Max(Gender) as Gender,count(*) as Strength from employee").show()

+------+--------+
|Gender|Strength|
+------+--------+
|  Male|    1469|
+------+--------+

In [0]:
# h)    Find the count of employee from which education fields
spark.sql("select EducationField, count(*) as Employee from employee group by EducationField order by Employee desc").show()

+----------------+--------+
|  EducationField|Employee|
+----------------+--------+
|   Life Sciences|     605|
|         Medical|     464|
|       Marketing|     159|
|Technical Degree|     132|
|           Other|      82|
| Human Resources|      27|
+----------------+--------+

In [0]:
 i) What is the job satisfaction level of employee?
spark.sql("select    JobSatisfaction , count(*) as Num_Employee from employee  group by JobSatisfaction order by Num_Employee desc").show()

Object `employee` not found.
+---------------+------------+
|JobSatisfaction|Num_Employee|
+---------------+------------+
|      Very High|         459|
|           High|         441|
|            Low|         289|
|         Medium|         280|
+---------------+------------+

In [0]:
# j)    Does most of employee do overtime: Yes or No?
spark.sql("select Overtime, count(*) as Num_Employee from employee where OverTime ='Yes' or Overtime ='No' group by Overtime ").show()

+--------+------------+
|Overtime|Num_Employee|
+--------+------------+
|      No|        1053|
|     Yes|         416|
+--------+------------+

In [0]:
# k)    Find Min & Max Salaried employees.
spark.sql("select Max(Income) as Max_salary,Min(Income) as Min_salary  from employee ").show()

+----------+----------+
|Max_salary|Min_salary|
+----------+----------+
|     19999|      1009|
+----------+----------+

In [0]:
# l) Does most of the employee do business travel? Find of the employees counts for each category   BusinessTravel   
spark.sql("select JobRole , count(*) as Num_Employee from employee where BusinessTravel ='Travel_Frequently' group by JobRole ").show()

+--------------------+------------+
|             JobRole|Num_Employee|
+--------------------+------------+
|     Sales Executive|          59|
|Manufacturing Dir...|          29|
|Laboratory Techni...|          51|
|Sales Representative|          23|
|Healthcare Repres...|          26|
|  Research Scientist|          54|
|             Manager|          13|
|   Research Director|          12|
|     Human Resources|          10|
+--------------------+------------+

In [0]:
# m)    Find the AVG salary of graduate employee.
spark.sql("select mean(Income) as Avg_salary  from employee where Education = 'Bachelor' ").show()

+-----------------+
|       Avg_salary|
+-----------------+
|6517.263986013986|
+-----------------+

In [0]:
#n)	Find the employee qualification receiving salary lower than equal to avg. salary of all employee. 
spark.sql("select Income, Education from employee where Income <= (select avg(Income) from employee)").show()

+------+-------------+
|Income|    Education|
+------+-------------+
|  5993|      College|
|  5130|Below College|
|  2090|      College|
|  2909|       Master|
|  3468|Below College|
|  3068|      College|
|  2670|     Bachelor|
|  2693|Below College|
|  5237|     Bachelor|
|  2426|     Bachelor|
|  4193|      College|
|  2911|Below College|
|  2661|      College|
|  2028|     Bachelor|
|  3298|      College|
|  2935|      College|
|  3944|     Bachelor|
|  4011|      College|
|  3407|       Master|
|  1232|      College|
+------+-------------+
only showing top 20 rows

In [0]:
#o)	When does the employee have highest chance of promotion in terms of working year
spark.sql("select Performance_Rating, count(*) as Promotion from employee group by Performance_Rating order by Promotion desc ").show()

+------------------+---------+
|Performance_Rating|Promotion|
+------------------+---------+
|         Excellent|     1243|
|       Outstanding|      226|
+------------------+---------+

In [0]:
#p)	Highest attrition is in which department?
spark.sql("select Department, count(*) as totalcount from employee  group by Department order by totalcount desc ").show()

+--------------------+----------+
|          Department|totalcount|
+--------------------+----------+
|Research & Develo...|       961|
|               Sales|       445|
|     Human Resources|        63|
+--------------------+----------+